### ISSUE TITLE
set -euo pipefail

### ISSUE THREAD

**Issue by H0neyBadger** [africanzoe/scripts#1]
https://github.com/africanzoe/scripts/blob/e2a7bb7aeba4d4ad5813042c21809b2ae6d42fda/getopts.template.sh#L2

**Comment by africanzoe** [comment]
What kind of error you get? Can you post the error please?

**Comment by africanzoe** [comment]
I'll add the options "-e" and "-o pipefail" and not "-u" as it could lead to an undesirable effect.
